version: "3.9"
services:
  app: 
    build:
      context: .
      dockerfile: apps/auth-nest/Dockerfile
      args:
        - ENV=development
    network_mode: "host"
    env_file:
      - .env
    ports:
      - "5000:5000"
    #depends_on:
    #  - postgres
    volumes:
      - .:/app:rw
    command: npm run start:dev
  
#  postgres:
#    image: postgres:alpine
#    restart: always
#    network_mode: "host"
#    ports:
#      - "5432:5432"
#    environment: 
#      - POSTGRES_PASSWORD=olakase123


  
  
