version: "3.9"

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/app:rw
      - /app/node_modules
    command: npm run start:dev
  
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=olakase123
  
  
